# Generated by Django 3.1.4 on 2021-04-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalVisitingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120)),
                ('your_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=120)),
                ('contact_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=180)),
                ('website', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='DigitalFacilities/DigitalVisitingCard')),
                ('category', models.CharField(choices=[('Business', 'Business'), ('Corporate', 'Corporate'), ('Festive', 'Festive'), ('Store', 'Store'), ('My Cards', 'My Cards')], max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalGreetingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text='From', max_length=60)),
                ('receiver', models.CharField(help_text='To', max_length=60)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Christmas', 'Christmas'), ('New Year', 'New Year'), ('Marriage', 'Marriage'), ('Birthday', 'Birthday'), ('My Cards', 'My Cards')], max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='DigitalFacilities/DigitalDiary')),
                ('start_date', models.DateField()),
                ('description', models.TextField()),
                ('reminder', models.BooleanField(default=True)),
                ('days_left', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
