# Generated by Django 3.1.4 on 2021-06-06 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210606_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('months', models.IntegerField()),
                ('price', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='land_mark',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptionplans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
