# Generated by Django 3.1.4 on 2021-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210606_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.TextField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='land_mark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
