# Generated by Django 3.1.4 on 2021-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('OutForDelivery', 'OutForDelivery')], default='Ordered', max_length=50),
        ),
    ]
