# Generated by Django 3.1.4 on 2021-08-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210805_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('OutForDelivery', 'OutForDelivery'), ('Canceled', 'Canceled')], default='Ordered', max_length=50),
        ),
    ]
