# Generated by Django 3.1.4 on 2021-08-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('ecommerce', '0008_remove_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon'),
        ),
    ]
