# Generated by Django 3.1.4 on 2021-08-10 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_order_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rew', models.CharField(choices=[('None', 'None'), ('Coupon', 'Coupon'), ('Product', 'Product')], max_length=20)),
                ('coupon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
