# Generated by Django 3.1.4 on 2021-08-10 06:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0009_order_coupon'),
        ('coupons', '0002_rewards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewards',
            new_name='Reward',
        ),
    ]
