# Generated by Django 3.1.4 on 2021-04-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('job_title', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=50)),
                ('your_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('industry', models.CharField(choices=[('Accountancy', 'Accountancy'), ('Business', 'Business'), ('Charity and Voluntary Work', 'Charity and Voluntary Work'), ('Creative Arts and Design', 'Creative Arts and Design'), ('Energy and Utilities', 'Energy and Utilities'), ('Creative Arts and Design', 'Creative Arts and Design'), ('Engineering and Manufacturing', 'Engineering and Manufacturing'), ('Environment and Agriculture', 'Environment and Agriculture'), ('Healthcare', 'Healthcare'), ('Hospitality and Event Management', 'Hospitality and Event Management'), ('Information Technology', 'Information Technology'), ('Law', 'Law'), ('Leisure, Sports, and Tourism', 'Leisure, Sports, and Tourism'), ('Marketing, Advertising, and PR', 'Marketing, Advertising, and PR'), ('Media and Internet', 'Media and Internet'), ('Property and Consultation', 'Property and Consultation'), ('Public Services and Administration', 'Public Services and Administration'), ('Recruitment and HR', 'Recruitment and HR'), ('Retail', 'Retail'), ('Sales', 'Sales'), ('Science and Pharmaceuticals', 'Science and Pharmaceuticals'), ('Social Care', 'Social Care'), ('Teacher Training and Education', 'Teacher Training and Education'), ('Transport and Logistics', 'Transport and Logistics')], max_length=80)),
                ('experience', models.CharField(max_length=20)),
                ('salary_from', models.CharField(max_length=20)),
                ('salary_to', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Job/Resume/')),
                ('date', models.DateField(auto_now_add=True)),
                ('saved', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Selected', 'Selected'), ('Not Selected', 'Not Selected'), ('Shortlisted', 'Shortlisted')], default='Applied', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.jobrecruiter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
