# Generated by Django 3.1.4 on 2021-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecruiter',
            name='company_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='jobrecruiter',
            name='job_title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='jobrecruiter',
            name='location',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='jobrecruiter',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
