# Generated by Django 3.1.4 on 2021-07-26 11:13

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210724_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecruiter',
            name='salary_from',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrecruiter',
            name='salary_to',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Job/Resume/', validators=[job.models.validate_file_extension]),
        ),
    ]
