# Generated by Django 3.1.4 on 2021-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210726_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecruiter',
            name='salary_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobrecruiter',
            name='salary_to',
            field=models.IntegerField(),
        ),
    ]
